### ISSUE TITLE
Android TableViews don't allow you to scroll back up

### ISSUE THREAD

**Issue by ucf713** [iskugor/Ti.SwipeRefreshLayout#10]
On Android, you cannot scroll back up if you have scrolled down the table. If you try, the pull to refresh will be activated.

If I substitute a ListView in place of the TableView, it works as expected.

**Comment by hardikamal** [comment]
Me too facing the same problem...Plz let me know if you get the solution...Thanks

**Comment by aggelos81** [comment]
I have made the fixes to the library available on my fork and made a distributable zip. Have already made a pull request for it to be added to this fork.

**Comment by iskugor** [comment]
@aggelos81 I can't see your pull request, could you make it? Thanks.

**Comment by aggelos81** [comment]
I tried to make one to your repository but instead it went on raymondkam's!
Στις 23 Ιουλ 2015 3:41 μμ, ο χρήστης "Ivan Škugor" <notifications@github.com>
έγραψε:

**Comment by aggelos81** [comment]
Alright made the request!

**Comment by iskugor** [comment]
@aggelos81 thank you :+1:
